apiVersion: v1      # string
kind: Pod           # string
metadata:           # dictionary 
  name: nginx       # must and could be any unique name
  labels:           # must  
    app: myapp      # custom application name // must
    tier: frontend
    env: production
spec:
  nodeName: node01
  containers:               # list of objects // name of the container within the POD // there could be multiple containers in a pod
  - name: nginx             # any name which makes sense to you // first element of the list
    image: nginx            # docker hub image name // or the fullname of the image in that image-repository.
 
  - name: abc_any_name       # second object of the list
    image: image_from_repo

 
# kubectl create -f pod.yaml (or) 
# kubectl apply -f pod.yaml      // APPLY is used when any changes are done on yaml file.


# another way to create a pod without yaml is
# kubectl run nginx --image=nginx  // simple way to create object


# EDIT command
# kubectl edit pod abc_pod       
# already pod create ayyindi but here manam image name or something edit chestunaam.
# ikkada oka k8 memory file lo oka yaml create ayyi live pod meeda changes apply avtaay
# but actual yaml remains same.
# so EDIT command use chesi then again, replace command use cheste better, yaml lo kooda changes apply avtay.
# kubectl replace -f abc_pod.yml 

# commands: https://learn.kodekloud.com/user/courses/cka-certification-course-certified-kubernetes-administrator/module/c6d2ac7d-8192-4cff-aa54-e36d888c5bd9/lesson/7814bc96-9352-4348-82f0-783f19cde47b

# kubectl run redis --image=redis:alpine --dry-run=client -o yaml > redis_pod.yml