apiVersion: v1
kind: Service
metadata:
  name: myapp-service


spec:
  type: LoadBalancer
  ports:
  - targetPort: 80
    port: 80            # must
    nodePort: 30008     # 30,000 - 32,767
  
  # this is to specify to which POD we are assigning the ports 
  selector:
    app: myapp          # this is the metadata content in a pod definition file
    type: front-end     # this is the metadata content in a pod definition file



# to create SERVICE
# kubectl create -f service-loadbalancer.yml

# to see list of SERVICES created
# kubectl get services

