apiVersion: v1
kind: Pod
metadata:
  name: redis123
  labels: 
    env: production
spec:
  containers:
  - name: redis123
    image: redis123


# by using command
# kubectl run redis --image=redis123 --dry-run=client -o yaml
# kubectl run redis --image=redis123 --dry-run=client -o yaml > redis.yaml

# after creating the yaml, run below command
# kubectl run -f redis.yaml
