apiVersion: v1
kind: Pod
metadata:
  name: voting_pod
  labels:
    app: voting_app
    type: frontend

spec:
  containers:
  - name: vote
    image: dockersamples/examplevotingapp_vote
    port:
      - containerPort: 80
        name: vote