apiVersion: v1
kind: Pod
metadata:
  name: db_pod
  labels:
    app: db_app
    type: backend

spec:
  containers:
  - name: postgres
    image: postgres:15-alpine
    port:
      - containerPort: 5432
        name: postgres