apiVersion: v1
kind: Pod
metadata:
  name: nginx-sleeper
  
spec:
  containers:
  - name: nginx-sleeper
    image: nginx-sleeper
    command: new_2.0           # entrypoint
    args: ["10"]               # this is the command