apiVersion: apps/v1
kind: Deployment

metadata:
  name: first-deployment
  labels: 
    type: front-end

spec:
  replicas: 3
  selector:
    matchLabels:
      type: front-end

  template:
    metadata: 
      name:
      labels: 
        app: practice-pods
        env: production
        type: front-end
    spec:
      containers:
      - name: nginx-container
        image: nginx:1.12
  
  
